### ISSUE TITLE
An Error Occurred, you should refresh the page.

### ISSUE THREAD

**Issue by enzofsilva** [zaffudo/CAH-Generator#6]
Hi all.

I'm trying to test this on my local machine (Mac OS X El Capitan) > Firefox / or Chrome.

the page displays properly and allows me to add the card text by lines, etc. But when generating the cards, they show fine on the screen in preview BUT I eventually get this message "An Error Occurred, you should refresh the page." and the Download button is grayed out.

I click "Close" and go back to the main page, the "Generating..." text is still there and grayed out as well.

**Comment by zaffudo** [comment]
I've not been able to work on this project in over a year, so off the top of my head, I'm probably can't offer any useful help.

Just to cover the basics - you're running a local server which supports PHP, you've got imageMagick, the local version of the site is generating cards, but the final step where they get zipped up and turned into a single download link is failing?

**Comment by zaffudo** [comment]
So after looking at this a bit, I have a feeling my latest commit should resolve this issue. There were still some hard coded paths in generator.php which would i noticed resulted in similar behavior on my local machine.

Also, as a side note, I found that the version of ImageMagick that I got via Homebrew on my Mac behaved a little differently than the version on my webhost and I had to tweak some of the values being passed to convert in order to get the text to line up well when running it on MacOS.
